service: death-star-serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${opt:stage}

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-plugin-typescript
