docker-build:
	docker build -f DeathStar.dockerfile -t death-star .

docker-run:
	docker run -p 8080:8080 death-star

# arn:aws:cloudformation:eu-central-1:260998989604:stack/GalacticEmpire-Pipeline/9717cab0-7e25-11ea-ab8c-06516a35da16